### ISSUE TITLE
EIP-4361: Add sign in with ethereum instead of normal text for signature

### ISSUE THREAD

**Issue by bigint** [aave/lens-api-examples#10]
![image](https://user-images.githubusercontent.com/69431456/157859705-aee01770-987e-4243-82b3-d34f778fcda0.png)

https://eips.ethereum.org/EIPS/eip-4361
https://login.xyz/

**Comment by joshstevens19** [comment]
nice idea !! didnt even know about that eip

**Comment by joshstevens19** [comment]
still draft EIP for now we will just keep the signing text as we got but its an easy change for us once eip becomes more used

**Comment by bigint** [comment]
Sure @joshstevens19 I'll keep an eye on the EIP once it's live I'll reopen this issue 🤗

**Comment by bigint** [comment]
yayyy!!!

**Comment by joshstevens19** [comment]
![telegram-cloud-photo-size-4-5845842436142774385-y](https://user-images.githubusercontent.com/18472422/173165967-8fda469f-779d-4524-87ae-11d41ff5f976.jpg)

this is done will deploy Monday morning!
