### ISSUE TITLE
Remove already followed user from `recommendation` endpoint

### ISSUE THREAD

**Issue by bigint** [aave/lens-api-examples#12]
If we already followed a user, i think there is no point in displaying again in recommended users

PS: this should be an unauthed request so any users can see what's recommended for other users

In twitter when I follow some user it popups the suggestion below

![Screenshot 2022-03-11 at 6 32 42 PM](https://user-images.githubusercontent.com/69431456/157871553-bb235bea-b9ab-48ad-8593-7c84c5b132ec.png)

**Comment by joshstevens19** [comment]
this is fixed but we looking at making the query faster as well closing here for now!
