### ISSUE TITLE
Add `isFollowing` and `isFollowed` field in `profile`

### ISSUE THREAD

**Issue by bigint** [aave/lens-api-examples#15]
Its very costly and causes bad ux to load `doesFollow` endpoint after the user profile got loaded

I suggest adding those two fields in `profile` endpoint itself

cc @joshstevens19

**Comment by joshstevens19** [comment]
For now, this makes our cache policy super hard hence why we do strip out this out into a different call. Twitter has this issue as well it just makes the query way too expensive to merge into one and invalidate when these things change. For now, we going to keep it separate queries. Twitter only renders "follows you" when you click a profile and also on the follower's list. We can look into extending the `following` and `followers` queries to bring these extra fields in later down the line but its a bit of scope for now!

**Comment by joshstevens19** [comment]
out of scope for now
