### ISSUE TITLE
Missing "prev" cursor info

### ISSUE THREAD

**Issue by iPaulPro** [aave/lens-api-examples#153]
### Problem
In V1 when querying notifications **without a cursor** the returned payload would include a `prev` and `next` object in the `pageInfo` cursor. In V2, the `prev` value is `null`. This prevents efficient queries for new notifications and requires extra client-side logic to track what is new.

### Proposed Solution

Always return a `prev` cursor value in paginated query payloads.

**Comment by iPaulPro** [comment]
Please let me know if there is a better place to report these issues...

**Comment by joshstevens19** [comment]
This is now fixed please try again
