### ISSUE TITLE
`timeline` endpoint returns the same post multiple times if it is collected

### ISSUE THREAD

**Issue by bigint** [aave/lens-api-examples#19]
`timeline` endpoint returns the same post multiple times if it is collected (I tried with feecollectmodule)

![image](https://user-images.githubusercontent.com/69431456/158522660-36f4b6ab-e97a-4f69-b868-88d2bf235b22.png)

**Comment by joshstevens19** [comment]
Guessing your wallet collected owns many profiles will look into

**Comment by joshstevens19** [comment]
so explained this over discord but basically was missing the 

```
 collectedBy {
    address
    defaultProfile {
      handle
   }
}
```
 
This means even though he was getting repeated posts in the timeline they meant different things they showed people he followed collecting that post!
