### ISSUE TITLE
Apollo Error in get-nfts in Mumbai

### ISSUE THREAD

**Issue by rtang03** [aave/lens-api-examples#30]
I guess this API does not require authentication. 

ownerAddress is copied from source repo.

Input
```text
query {
  nfts(
    request: {
      ownerAddress: "0x54be3a794282c030b15e43ae2bb182e14c409c5e"
      chainIds: [80001]
      limit:10
    }
  ) {
    items {
      tokenId
    }
  }
}
```

After a couple of minutes, Output
```json
{
  "error": "Unexpected token < in JSON at position 0"
}
```

**Comment by joshstevens19** [comment]
Our provider is quite slow sometimes we looking at changing providers to make this faster! Will look at this query for you

**Comment by rtang03** [comment]
Great Thank you.
