### ISSUE TITLE
Throw error when submit transaction to "Follow"

### ISSUE THREAD

**Issue by rtang03** [aave/lens-api-examples#32]
Source: https://github.com/aave/lens-api-examples/blob/master/src/follow/follow.ts#L73

I tried to mimic the call from above source, simplified as below:

```
const contract = new ethers.Contract("0xd7B3481De00995046C7850bCe9a5196B7605c367", LENS_HUB_ABI, signer);
const tx = contract.followWithSig({
        follower: address,
        profileIds: typedData?.value?.profileIds,
        datas: typedData?.values?.datas,
        sig: {
          v,
          r,
          s,
          deadline: typedData.value.deadline,
        },
      })
```

It gives below errors. 

```text
Error: invalid address or ENS name (argument="name", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.5.0)
```

The error is thrown by ethersJs

I was able to create-post, using the similar code snippet, and works well. But `Follow` does not work. 

I am not clue whether it is my issue, or something else.

**Comment by joshstevens19** [comment]
spoke on discord is an array in your code itself!

**Comment by rtang03** [comment]
Thanks, I catch it
