### ISSUE TITLE
`collectedBy` always returns null even if the post is collected

### ISSUE THREAD

**Issue by bigint** [aave/lens-api-examples#33]
`0x13-0x2c`

![Screenshot 2022-03-21 at 9 00 49 AM](https://user-images.githubusercontent.com/69431456/159201751-aa335a7e-a718-4aa4-a489-b804fd611f7d.png)

**Comment by bigint** [comment]
cc @joshstevens19

**Comment by joshstevens19** [comment]
CollectBy is only ever filled in when on timeline to allow you to show who collected everything else it is never used and will always be null. Putting this on the main schema of post and comment allowed easy caching for clients!
