### ISSUE TITLE
Add full text search for API endpoint

### ISSUE THREAD

**Issue by BellangerSebastien** [aave/lens-api-examples#51]
Add full text search via the postgre SQL plain text search module (the database you use in the back-end). Before you can use a more powerful search engine (ElasticSearch ...)

https://www.postgresql.org/docs/current/textsearch-intro.html#TEXTSEARCH-INTRO-CONFIGURATIONS

**Comment by bigint** [comment]
+1

**Comment by joshstevens19** [comment]
The actually text of the publication is not stored in the Postgres database as it would bloat it. It’s stored on s3 a full text search is coming after mainnet launch. Closing for now as this is a roadmap item not an issue.
