### ISSUE TITLE
Add advanced where conditions for filtering items in a query

### ISSUE THREAD

**Issue by bigint** [aave/lens-api-examples#6]
![image](https://user-images.githubusercontent.com/69431456/157680052-b0110a0a-4a57-4da9-be14-b8b56ea06f28.png)

**Comment by joshstevens19** [comment]
we not going to overload with generic filters - this, in theory, is bad practice for sure for speed! it's much better if you find something you NEED to do and no filters exist then let us know and we add them as we go. This way we avoid code bloat, slow queries, and a more complex request interface for stuff nobody users.
