### ISSUE TITLE
Ability to retrieve profiles without targeting them individually

### ISSUE THREAD

**Issue by m1guelpf** [aave/lens-api-examples#63]
Right now, you can only batch get profiles by their IDs or their handles. It'd be cool to be able to say "get me 50 profiles, filtered by the most followers/posts/etc."

Somewhat related to #31?

**Comment by joshstevens19** [comment]
`exploreProfiles` now exists which takes filters

```
export enum ProfileSortCriteria {
  CREATED_ON = 'CREATED_ON',
  MOST_FOLLOWERS = 'MOST_FOLLOWERS',
  LATEST_CREATED = 'LATEST_CREATED',
  MOST_POSTS = 'MOST_POSTS',
  MOST_COMMENTS = 'MOST_COMMENTS',
  MOST_MIRRORS = 'MOST_MIRRORS',
  MOST_PUBLICATION = 'MOST_PUBLICATION',
  MOST_COLLECTS = 'MOST_COLLECTS',
}
```

will do docs for it monday but this is now deployed and can be used

🔥
