### ISSUE TITLE
Get publications by ID ordered by Inputs

### ISSUE THREAD

**Issue by BellangerSebastien** [aave/lens-api-examples#68]
We would like to be able to retrieve the publications by order of ids passed in parameters.

Example: 

We want the ids 9,2,10,6 and the API return publication by this order : 9,2,10,6

Today, the API returns the items by order of publication date or id:  2-6-9-10.

**Comment by joshstevens19** [comment]
Hey you can order this yourself quite easily after response.. the API will always order by created date for now (until we expand for other sorting options) so because this is super simple your side closing this issue! 👍
