### ISSUE TITLE
Filter timeline by publicationTypes

### ISSUE THREAD

**Issue by BellangerSebastien** [aave/lens-api-examples#70]
it could be cool to filter the timeline by :  publicationTypes: [POST, COMMENT, MIRROR],

Thanks ! 💙

**Comment by sasicodes** [comment]
+1

**Comment by joshstevens19** [comment]
timelineType now exposed on the timeline posts and mirrors come together but you can grab all the timeline "events" you care about post will give back mirror or post for now!
