### ISSUE TITLE
API should not answer with HTTP code 200 when user is not authenticated

### ISSUE THREAD

**Issue by starwalker00** [aave/lens-api-examples#76]
Hello,

When a request is made without authentication data (access-token HTTP header), the API answers with HTTP CODE 200 and populates the `errors` field in the response describing precisely this error.
I think it would be better for it to answer with a breaking code, probably 401.

**Comment by joshstevens19** [comment]
hey graphql does not use http codes.. the API is graphql not HTTP protocol!
